version: '3.1'
services:
  emlakjet_java_service:
    image: emlakjet_java_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - emlakjet-network
    depends_on:
      - emlakjet_postgres
  emlakjet_postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=emlakjet
    networks:
      - emlakjet-network

networks:
  emlakjet-network:
    driver: bridge