spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/emlakjet
    username: root
    password: password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
application:
  base-url: localhost:8080
  billing:
    limit: 200
  messages:
    base-name: message
    default-locale: tr